PLUGIN_NAME=		nebula
PLUGIN_VERSION=		1.0
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		A scalable overlay networking tool with a focus on performance, simplicity and security
PLUGIN_MAINTAINER=	walnuss0815@gmail.com

.include "../../Mk/plugins.mk"
